apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::719256692338:role/eksctl-eksctl-demo-nodegroup-ng-a-NodeInstanceRole-64QV8MHF8N4L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::719256692338:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-23T00:19:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1791"
  uid: 356bc06a-c11c-41aa-a8f5-78fc6a34c276
